name: Release
on:
  push:
    branches:
      - test
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run semantic-release
        run: yarn install && yarn global add semantic-release@17.4.4 && semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}